import type { CardDefinition } from './types'

export const CARD_DEFINITIONS: CardDefinition[] = [
  // ─── Power-Ups (good holes) ────────────────────────────────────────────────
  {
    key: 'beer_can_gimme',
    name: 'Beer Can Gimme',
    description: 'Each drink consumed this round grants a gimme radius of one club head length. Tap your drink counter. Four drinks = four club heads of gimme. Group-verified.',
    type: 'power_up',
    trigger: 'eagle_or_ace',
    timing: 'Any hole, before putting',
    isNsfw: true,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'mulligan',
    name: 'Mulligan',
    description: 'Re-take any one shot this hole. Only the second attempt counts. Cannot be used on a conceded putt.',
    type: 'power_up',
    trigger: 'birdie',
    timing: 'During the hole, before submitting',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'foot_wedge',
    name: 'Foot Wedge',
    description: 'Move your ball one club length in any direction, no penalty. Works from any lie including hazards. Cannot move onto the green or into the hole.',
    type: 'power_up',
    trigger: 'birdie',
    timing: 'During the hole, before your next shot',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'breakfast_ball',
    name: 'Breakfast Ball',
    description: 'Re-hit your tee shot on any par 4 or par 5. Keep whichever ball you prefer. The original shot never happened.',
    type: 'power_up',
    trigger: 'birdie',
    timing: 'Tee box only, before others tee off',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'stroke_shield',
    name: 'Stroke Shield',
    description: 'Block the next penalty card played against you. It bounces back to the sender — they must play it on themselves next hole instead.',
    type: 'power_up',
    trigger: 'birdie_back_to_back',
    timing: 'Auto-activates when a penalty card is played against you',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'gimme_putt',
    name: 'Gimme Putt',
    description: 'Concede your own putt from inside six feet. Score what you would have made.',
    type: 'power_up',
    trigger: 'birdie',
    timing: 'On the green, before putting',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'winter_rules',
    name: 'Winter Rules',
    description: 'Improve your lie anywhere on the course for one hole. Up to one club length, no closer to the hole. No penalty.',
    type: 'power_up',
    trigger: 'birdie',
    timing: 'Declared before the hole begins',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'skip_hole',
    name: 'Skip Hole',
    description: 'Score par on the next hole without playing it. Walk to the next tee. Everyone else still plays.',
    type: 'power_up',
    trigger: 'eagle',
    timing: 'Declared on the tee box',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },

  // ─── Opponent Penalties (good holes — deal to opponent) ───────────────────
  {
    key: 'reverse_mulligan',
    name: 'Reverse Mulligan',
    description: 'Target player must re-take their best shot from this hole — the good one. They play again from the same spot and keep the second result.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole',
    isNsfw: false,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'blue_shell',
    name: 'Blue Shell',
    description: 'Add +1 stroke to the current leaderboard leader\'s score on this hole. Cannot be blocked.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole, auto-applies to leader',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'the_yips',
    name: 'The Yips',
    description: 'Target player must putt one-handed on the next green. Their choice of hand. Group must verify before score is submitted.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole',
    isNsfw: false,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'wrong_club',
    name: 'Wrong Club',
    description: 'Target player must hit their tee shot with a club chosen by the group. Anything except the driver. Group votes before the tee shot.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole, tee shot only',
    isNsfw: false,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'sandtrap_tax',
    name: 'Sandtrap Tax',
    description: 'If target player\'s ball lands in any bunker on the next hole, they take +1 automatic penalty stroke on top of the bunker shot.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole, auto-applies if bunker',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'caddie_swap',
    name: 'Caddie Swap',
    description: 'Target player must take all club selection advice from a group member designated by the card sender for the next hole.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole',
    isNsfw: false,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'cart_path_only',
    name: 'Cart Path Only',
    description: 'Target player must play their ball wherever it lies with no relief for the next hole. No free drops from any lie.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: next hole',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'happy_hour',
    name: 'Happy Hour',
    description: 'Target player must finish their current drink before teeing off on the next hole. If not holding one, they must get one first. Session host enforces responsibly.',
    type: 'penalty',
    trigger: 'birdie',
    timing: 'Opponent must play: before next tee shot',
    isNsfw: true,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },

  // ─── Self Penalties (bad holes — auto-applied) ────────────────────────────
  {
    key: 'walk_of_shame',
    name: 'Walk of Shame',
    description: 'You must walk to your ball on the next hole — no cart. If already walking, carry someone else\'s bag for one hole.',
    type: 'self_penalty',
    trigger: 'triple_bogey_or_worse',
    timing: 'You must play: next hole',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: true,
  },
  {
    key: 'tin_cup',
    name: 'Tin Cup',
    description: 'Use the same club for every shot on the next hole — tee through putt. Group picks the club.',
    type: 'self_penalty',
    trigger: 'double_bogey',
    timing: 'You must play: next hole',
    isNsfw: false,
    requiresGroupVerify: true,
    requiresPhysical: true,
  },
  {
    key: 'grip_it_and_rip_it',
    name: 'Grip It and Rip It',
    description: 'You must use driver off the tee on the next hole regardless of yardage or layout. No exceptions.',
    type: 'self_penalty',
    trigger: 'double_bogey',
    timing: 'You must play: next tee shot',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'honest_abe',
    name: 'Honest Abe',
    description: 'You play the next hole with no handicap strokes applied. Full gross score counts. No net adjustments.',
    type: 'self_penalty',
    trigger: 'bogey',
    timing: 'You must play: next hole, auto-applies to scoring',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },

  // ─── Opponent Boosts (bad holes — auto-granted to opponents) ──────────────
  {
    key: 'steal_a_stroke',
    name: 'Steal a Stroke',
    description: 'The benefiting opponent subtracts one stroke from their score on any future hole this round. Must be declared before teeing off on that hole.',
    type: 'opponent_boost',
    trigger: 'bogey',
    timing: 'Opponent plays: next hole',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'free_drop',
    name: 'Free Drop',
    description: 'Opponent gets a free drop from any single lie on the next hole — rough, hazard, or divot — no penalty, up to two club lengths relief.',
    type: 'opponent_boost',
    trigger: 'double_bogey',
    timing: 'Opponent plays: next hole',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'extra_gimme',
    name: 'Extra Gimme',
    description: 'Opponent gets a gimme from anywhere inside the leather on the next hole. No group vote required.',
    type: 'opponent_boost',
    trigger: 'bogey',
    timing: 'Opponent plays: next hole',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
  {
    key: 'opponent_breakfast_ball',
    name: 'Breakfast Ball (Opponent)',
    description: 'Opponent gets a free re-hit off the next tee. They keep whichever ball is better. A gift from your misery.',
    type: 'opponent_boost',
    trigger: 'triple_bogey_or_worse',
    timing: 'Opponent plays: next tee shot',
    isNsfw: false,
    requiresGroupVerify: false,
    requiresPhysical: false,
  },
]

export const CARDS_BY_KEY: Record<string, CardDefinition> = Object.fromEntries(
  CARD_DEFINITIONS.map((c) => [c.key, c])
)
